// Filename: Tiles.h
// Tiles should be #define'd here. Each different kind of tile has a corresponding number to represent it.
// These tile numbers are generated by the 3rd party application named "Tiled" and can be found in the 
// *.tmx file that Tiled generates.
//
// Project Codename: GameB
// TODO: Come up with a better name later.
// 2020 Joseph Ryan Ries <ryanries09@gmail.com>
// My YouTube series where we program an entire video game from scratch in C.
// Watch it on YouTube:    https://www.youtube.com/watch?v=3zFFrBSdBvA
// Follow along on GitHub: https://github.com/ryanries/GameB
// Find me on Twitter @JosephRyanRies 
// # License
// ----------
// The source code in this project is licensed under the MIT license.
// The media assets such as artwork, custom fonts, music and sound effects are licensed under a separate license.
// A copy of that license can be found in the 'Assets' directory.
// stb_vorbis by Sean Barrett is public domain and a copy of its license can be found in the stb_vorbis.c file.

#pragma once

#define TILE_GRASS_01	1

#define TILE_WATER_01	2

#define TILE_DEBUG_01	3

#define TILE_BRICK_01	4

#define TILE_PORTAL_01	5

#define TILE_SAND_01	10

#define TILE_SNOW_01	13

#define TILE_TREES_01	16	// Temperate trees

#define TILE_TREES_02	22	// Desert trees

#define TILE_TREES_03	23	// Snowy trees

#define TILE_SWAMP_01	19

#define TILE_HOUSE_01	26

#define TILE_BRIDGE_01	18